build:
  version: "1.0"

accounts:
  message: "Welcome to Bank accounts related prod APIs "
  contactDetails:
    name: "Kartikeya Gupta - Developer"
    email: "kartikeyayash4@gmail.com"
  onCallSupport:
    - 8707336016
