build:
  version: "2.0"

cards:
  message: "Welcome to Bank Cards related QA APIs "
  contactDetails:
    name: "Kartikeya Gupta - Developer"
    email: "kartikeyayash4@gmail.com"
  onCallSupport:
    - 8707336016
