
build:
  version: "3.0"

cards:
  message: "Welcome to Bank Cards related local APIs "
  contactDetails:
    name: "Kartikeya Gupta - Developer"
    email: "kartikeyayash4@gmail.com"
  onCallSupport:
    - 8707336016