#spring:
#  config:
#    activate:
#      on-profile: "production"

build:
  version: "1.0"

cards:
  message: "Welcome to Bank Cards related prod APIs "
  contactDetails:
    name: "Kartikeya Gupta - Developer"
    email: "kartikeyayash4@gmail.com"
  onCallSupport:
    - "8707336016"
