#spring:
#  config:
#    activate:
#      on-profile: "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to Bank Loans related QA APIs "
  contactDetails:
    name: "Kartikeya Gupta - Developer"
    email: "kartikeyayash4@gmail.com"
  onCallSupport:
    - 8707336016