#spring:
#  config:
#    activate:
#      on-profile: "production"
build:
  version: "1.0"


loans:
  message: "Welcome to Bank Loans related production APIs "
  contactDetails:
    name: "Kartikeya Gupta - Developer"
    email: "kartikeyayash4@gmail.com"
  onCallSupport:
    - 8707336016